#!/usr/bin/env python
import optparse
import sys

optparser = optparse.OptionParser()
optparser.add_option("-a", "--input1", dest="input1", default="../data/train/all_features.train", help="Full training baseline features list (input)")
optparser.add_option("-b", "--input2", dest="input2", default="../data/test/all_features.test", help="Full testing baseline features list (input)")
optparser.add_option("-c", "--output1", dest="output1", default="added_overall.train", help="Added training features list (output)")
optparser.add_option("-d", "--output2", dest="output2", default="added_overall.test", help="Added testing features list (output)")
optparser.add_option("-e", "--source1", dest="source1", default="../data/train/en-es_source.train", help="Source training sentences")
optparser.add_option("-f", "--source2", dest="source2", default="../data/test/en-es_source.test", help="Source testing sentences")
optparser.add_option("-g", "--target1", dest="target1", default="../data/train/en-es_target.train", help="Target training sentences")
optparser.add_option("-i", "--target2", dest="target2", default="../data/test/en-es_target.test", help="Target testing sentences")
(opts, _) = optparser.parse_args()

def get_num_untrans_words(source_sen, target_sen):
	source_words = source_sen.split()
	target_words = target_sen.split()
	num_untrans_words = 0
	for word in target_words:
		if word in source_words:
			num_untrans_words += 1
	return num_untrans_words

# TRAINING
all_data1 = [pair for pair in zip(open(opts.source1), open(opts.target1), open(opts.input1))]
my_file1 = open(opts.output1, 'w')
for (source_sen, target_sen, features) in all_data1:
  # Number of untranslated words
  num_untrans_words = get_num_untrans_words(source_sen, target_sen)
  # Write the file
  my_file1.write(features.rstrip() + " " + str(num_untrans_words) + "\n")
my_file1.close()

# TESTING
all_data2 = [pair for pair in zip(open(opts.source2), open(opts.target2), open(opts.input2))]
my_file2 = open(opts.output2, 'w')
for (source_sen, target_sen, features) in all_data2:
  # Number of untranslated words
  num_untrans_words = get_num_untrans_words(source_sen, target_sen)
  # Write the file
  my_file2.write(features.rstrip() + " " + str(num_untrans_words) + "\n")
my_file2.close()

